# Generated by Django 3.1.4 on 2021-01-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_app',
            fields=[
                ('app_name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='name')),
                ('app_level', models.CharField(blank=True, max_length=2, null=True, verbose_name='level')),
                ('app_sname', models.CharField(blank=True, max_length=16, null=True, verbose_name='sname')),
            ],
        ),
        migrations.CreateModel(
            name='t_db_schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(choices=[('db', 'db'), ('dg', 'dg'), ('rac', 'rac'), ('single', 'single')], max_length=8, unique=True, verbose_name='schema')),
            ],
        ),
        migrations.CreateModel(
            name='t_hosts',
            fields=[
                ('location', models.CharField(blank=True, max_length=10, null=True, verbose_name='loc')),
                ('ip', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, verbose_name='ip')),
                ('is_rdcheck', models.BooleanField(null=True, verbose_name='is_rdcheck')),
                ('os_type', models.CharField(blank=True, choices=[('linux', 'linux'), ('aix', 'aix'), ('windows', 'windows')], max_length=16, null=True, verbose_name='os_type')),
                ('os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='version')),
                ('device', models.CharField(blank=True, max_length=1, null=True, verbose_name='device')),
                ('db_type', models.CharField(blank=True, choices=[('oracle', 'oracle'), ('informix', 'informix'), ('db2', 'db2'), ('mysql', 'mysql')], max_length=16, null=True, verbose_name='db_type')),
                ('hostname', models.CharField(blank=True, max_length=32, null=True, verbose_name='hostname')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='ts')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcheck.t_app')),
                ('db_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcheck.t_db_schema')),
            ],
        ),
    ]
