# Generated by Django 3.1.4 on 2020-12-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linux_res',
            name='gmt_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='gmt_create'),
        ),
    ]
