# Generated by Django 3.1.4 on 2021-01-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_hosts',
            name='db_type',
            field=models.CharField(blank=True, choices=[('oracle', 'oracle'), ('informix', 'informix'), ('db2', 'db2'), ('mysql', 'mysql')], max_length=16, null=True, verbose_name='数据库模式'),
        ),
        migrations.AlterField(
            model_name='t_hosts',
            name='device',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='t_hosts',
            name='hostname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='t_hosts',
            name='is_rdcheck',
            field=models.BooleanField(null=True, verbose_name='是否巡检'),
        ),
        migrations.AlterField(
            model_name='t_hosts',
            name='os_type',
            field=models.CharField(blank=True, choices=[('linux', 'linux'), ('aix', 'aix'), ('windows', 'windows')], max_length=16, null=True, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='t_hosts',
            name='os_version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='t_hosts',
            name='ts',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
        migrations.CreateModel(
            name='t_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='ts')),
                ('metirc', models.JSONField(null=True, verbose_name='metric')),
                ('ext', models.JSONField(null=True, verbose_name='ext')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcheck.t_hosts')),
            ],
        ),
    ]
