# Generated by Django 3.1.4 on 2021-01-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcheck', '0002_auto_20201229_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='name')),
                ('app_level', models.CharField(blank=True, max_length=2, null=True, verbose_name='level')),
            ],
        ),
        migrations.CreateModel(
            name='t_db_schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(choices=[('db', 'db'), ('dg', 'dg'), ('rac', 'rac'), ('pri', 'pri'), ('std', 'std')], max_length=8, verbose_name='schema')),
            ],
        ),
        migrations.DeleteModel(
            name='linux_res',
        ),
    ]
