# Generated by Django 3.1.4 on 2021-01-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcheck', '0003_auto_20210116_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_hosts',
            name='device',
            field=models.CharField(blank=True, choices=[('V', '虚拟机'), ('P', '物理机')], max_length=16, null=True, verbose_name='设备类型'),
        ),
    ]
