# Generated by Django 3.1.4 on 2021-01-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcheck', '0004_auto_20210116_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_hosts',
            name='db_type',
            field=models.CharField(blank=True, choices=[('oracle', 'oracle'), ('informix', 'informix'), ('db2', 'db2'), ('mysql', 'mysql')], max_length=16, null=True, verbose_name='数据库'),
        ),
    ]
