# Generated by Django 3.1.4 on 2021-01-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcheck', '0005_auto_20210116_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_db_schema',
            name='schema',
            field=models.CharField(choices=[('db', 'db'), ('dg', 'dg'), ('rac', 'rac'), ('single', 'single')], max_length=8, unique=True, verbose_name='数据库模式'),
        ),
    ]
