# Generated by Django 3.1.4 on 2021-01-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdcheck', '0006_auto_20210116_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_db_schema',
            options={'verbose_name': '数据库模式'},
        ),
    ]
