# Generated by Django 3.1.4 on 2021-01-16 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('rdcheck', '0008_auto_20210116_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_hosts',
            name='app',
        ),
        migrations.RemoveField(
            model_name='t_hosts',
            name='db_schema',
        ),
        migrations.AlterField(
            model_name='t_result',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.t_hosts'),
        ),
        migrations.DeleteModel(
            name='t_app',
        ),
        migrations.DeleteModel(
            name='t_db_schema',
        ),
        migrations.DeleteModel(
            name='t_hosts',
        ),
    ]
