# Generated by Django 3.1.4 on 2021-01-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210116_1840'),
        ('rdcheck', '0009_auto_20210116_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t_result',
            new_name='t_linux_result',
        ),
        migrations.AlterModelOptions(
            name='t_linux_result',
            options={'verbose_name': 'linux巡检结果', 'verbose_name_plural': 'linux巡检结果'},
        ),
        migrations.CreateModel(
            name='t_oracle_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='ts')),
                ('metirc', models.JSONField(null=True, verbose_name='metric')),
                ('ext', models.JSONField(null=True, verbose_name='ext')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.t_hosts')),
            ],
            options={
                'verbose_name': 'oracle巡检结果',
                'verbose_name_plural': 'oracle巡检结果',
            },
        ),
    ]
