# Generated by Django 3.1.4 on 2021-01-16 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_app',
            fields=[
                ('app_name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='name')),
                ('app_level', models.CharField(blank=True, max_length=2, null=True, verbose_name='level')),
                ('app_sname', models.CharField(blank=True, max_length=16, null=True, verbose_name='sname')),
            ],
        ),
        migrations.CreateModel(
            name='t_db_schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(choices=[('db', 'db'), ('dg', 'dg'), ('rac', 'rac'), ('single', 'single')], max_length=8, unique=True, verbose_name='模式')),
            ],
        ),
        migrations.CreateModel(
            name='t_hosts',
            fields=[
                ('location', models.CharField(blank=True, max_length=10, null=True, verbose_name='loc')),
                ('ip', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, verbose_name='ip')),
                ('is_rdcheck', models.BooleanField(null=True, verbose_name='是否巡检')),
                ('os_type', models.CharField(blank=True, choices=[('linux', 'linux'), ('aix', 'aix'), ('windows', 'windows')], max_length=16, null=True, verbose_name='OS')),
                ('os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='版本')),
                ('device', models.CharField(blank=True, choices=[('V', '虚拟机'), ('P', '物理机')], max_length=16, null=True, verbose_name='设备类型')),
                ('db_type', models.CharField(blank=True, choices=[('oracle', 'oracle'), ('informix', 'informix'), ('db2', 'db2'), ('mysql', 'mysql')], max_length=16, null=True, verbose_name='数据库')),
                ('hostname', models.CharField(blank=True, max_length=32, null=True, verbose_name='主机名')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.t_app')),
                ('db_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.t_db_schema', verbose_name='数据库模式')),
            ],
            options={
                'verbose_name': '主机表',
            },
        ),
    ]
