# Generated by Django 3.1.4 on 2021-01-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_app',
            options={'verbose_name': '应用表', 'verbose_name_plural': '应用表'},
        ),
        migrations.AlterModelOptions(
            name='t_hosts',
            options={'verbose_name': '主机表', 'verbose_name_plural': '主机表'},
        ),
        migrations.AlterField(
            model_name='t_app',
            name='app_level',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='t_app',
            name='app_name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='应用名'),
        ),
        migrations.AlterField(
            model_name='t_app',
            name='app_sname',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='英文简称'),
        ),
        migrations.AlterField(
            model_name='t_db_schema',
            name='schema',
            field=models.CharField(choices=[('db', 'db'), ('dg', 'dg'), ('rac', 'rac'), ('single', 'single'), (None, '无')], max_length=8, unique=True, verbose_name='模式'),
        ),
        migrations.AlterField(
            model_name='t_hosts',
            name='db_type',
            field=models.CharField(blank=True, choices=[('oracle', 'oracle'), ('informix', 'informix'), ('db2', 'db2'), ('mysql', 'mysql'), (None, '无')], max_length=16, null=True, verbose_name='数据库'),
        ),
    ]
