# Generated by Django 3.1.4 on 2021-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210116_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_hosts',
            name='db_schema',
            field=models.CharField(choices=[('db', 'db'), ('dg', 'dg'), ('rac', 'rac'), ('single', 'single'), (None, '无')], max_length=16, null=True, verbose_name='数据库模式'),
        ),
        migrations.DeleteModel(
            name='t_db_schema',
        ),
    ]
